/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MarketIndexImport } from './routes/market/index'
import { Route as MarketItemIdIndexImport } from './routes/market/$itemId/index'
import { Route as MarketItemIdMdmImport } from './routes/market/$itemId/mdm'
import { Route as MarketItemIdGImport } from './routes/market/$itemId/g'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MarketIndexRoute = MarketIndexImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRoute,
} as any)

const MarketItemIdIndexRoute = MarketItemIdIndexImport.update({
  id: '/market/$itemId/',
  path: '/market/$itemId/',
  getParentRoute: () => rootRoute,
} as any)

const MarketItemIdMdmRoute = MarketItemIdMdmImport.update({
  id: '/market/$itemId/mdm',
  path: '/market/$itemId/mdm',
  getParentRoute: () => rootRoute,
} as any)

const MarketItemIdGRoute = MarketItemIdGImport.update({
  id: '/market/$itemId/g',
  path: '/market/$itemId/g',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketIndexImport
      parentRoute: typeof rootRoute
    }
    '/market/$itemId/g': {
      id: '/market/$itemId/g'
      path: '/market/$itemId/g'
      fullPath: '/market/$itemId/g'
      preLoaderRoute: typeof MarketItemIdGImport
      parentRoute: typeof rootRoute
    }
    '/market/$itemId/mdm': {
      id: '/market/$itemId/mdm'
      path: '/market/$itemId/mdm'
      fullPath: '/market/$itemId/mdm'
      preLoaderRoute: typeof MarketItemIdMdmImport
      parentRoute: typeof rootRoute
    }
    '/market/$itemId/': {
      id: '/market/$itemId/'
      path: '/market/$itemId'
      fullPath: '/market/$itemId'
      preLoaderRoute: typeof MarketItemIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market': typeof MarketIndexRoute
  '/market/$itemId/g': typeof MarketItemIdGRoute
  '/market/$itemId/mdm': typeof MarketItemIdMdmRoute
  '/market/$itemId': typeof MarketItemIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market': typeof MarketIndexRoute
  '/market/$itemId/g': typeof MarketItemIdGRoute
  '/market/$itemId/mdm': typeof MarketItemIdMdmRoute
  '/market/$itemId': typeof MarketItemIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/market/': typeof MarketIndexRoute
  '/market/$itemId/g': typeof MarketItemIdGRoute
  '/market/$itemId/mdm': typeof MarketItemIdMdmRoute
  '/market/$itemId/': typeof MarketItemIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/market'
    | '/market/$itemId/g'
    | '/market/$itemId/mdm'
    | '/market/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/market'
    | '/market/$itemId/g'
    | '/market/$itemId/mdm'
    | '/market/$itemId'
  id:
    | '__root__'
    | '/'
    | '/market/'
    | '/market/$itemId/g'
    | '/market/$itemId/mdm'
    | '/market/$itemId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MarketItemIdGRoute: typeof MarketItemIdGRoute
  MarketItemIdMdmRoute: typeof MarketItemIdMdmRoute
  MarketItemIdIndexRoute: typeof MarketItemIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketIndexRoute: MarketIndexRoute,
  MarketItemIdGRoute: MarketItemIdGRoute,
  MarketItemIdMdmRoute: MarketItemIdMdmRoute,
  MarketItemIdIndexRoute: MarketItemIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/market/",
        "/market/$itemId/g",
        "/market/$itemId/mdm",
        "/market/$itemId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/market/": {
      "filePath": "market/index.tsx"
    },
    "/market/$itemId/g": {
      "filePath": "market/$itemId/g.tsx"
    },
    "/market/$itemId/mdm": {
      "filePath": "market/$itemId/mdm.tsx"
    },
    "/market/$itemId/": {
      "filePath": "market/$itemId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
