[package]
name = "market"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
universe.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
futures.workspace = true