[package]
name = "data_fetcher"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
reqwest.workspace = true
esi.workspace = true
rlimit.workspace = true
chrono.workspace = true
dashmap.workspace = true