[package]
name = "universe"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
futures.workspace = true